version: 1

formatters:
  brief:
    format: "%(asctime)s %(message)s"

  simple:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'

  complex:
      format: "%(asctime)s [%(levelname)s] %(name)s, line %(lineno)d: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  file:
    class : logging.handlers.RotatingFileHandler
    level: INFO
    formatter: complex
    filename: symbtiotic.log
    maxBytes: 4096
    backupCount: 2

loggers:
  default: &default
    handlers: [console, file]
    propagate: no

  services:
    <<: *default

  devices:
    <<: *default

root:
  level: DEBUG
  handlers: [console]
